### ISSUE TITLE
UnboundLocalError: cannot access local variable 'height' where it is not associated with a value

### ISSUE THREAD

**Issue by SeppeVanSteenbergen** [arnaudmiribel/streamlit-dataframe-summary#2]
#### Current Behavior
When calling `dataframe_with_summary_stats`, the `height` argument must be explicitly provided or you would run into `UnboundLocalError`. The function only assigns a value to `height` if `"height"` is a key in the `kwargs` dictionary:
```python
if "height" in kwargs:
    height = kwargs["height"]
```

#### Proposed solution
To handle cases where `"height"` is not in `kwargs`, a default value of `None` can be assigned:
```python
height = kwargs.get("height", None)
```
However, this approach causes misalignment in side-by-side mode, as the `dataframe` and `summary_stats` have different flexible heights.

#### Suggested Fix
To ensure consistent height alignment, set a default value for `"height"` in the `kwargs` dictionary if it does not exist. This can be done at the beginning of the function for all display types or specifically for side-by-side mode:
```python
kwargs.setdefault("height", 400)
```
Note: If a default value is set for all display types, the proposed solution above is not even needed as `"height"` will always be present in `kwargs`.

#### Impact
This is a minor change but can be useful for maintaining consistent layout and improving usability.

**Comment by arnaudmiribel** [comment]
Hey @SeppeVanSteenbergen, this is great feedback! Definitely didn't want `height` to block people. Will add a default value
